repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0  # this is optional, use `pre-commit autoupdate` to get the latest rev!
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.3
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.14.1
  hooks:
    - id: mypy
      stages: [pre-commit, pre-push]
      args: ['--config-file', 'pyproject.toml']
      additional_dependencies:
        - atomium
        - numpy
        - pydantic
        - pytest
        - rdkit

- repo: local
  hooks:
  - id: Pytest
    name: pytest
    stages: [pre-commit]
    types: [python]
    entry: pytest
    language: system
    pass_filenames: false
